"""make update timestamp nullable

Revision ID: b14eba0548ae
Revises: f90df87e03bd
Create Date: 2026-09-01 02:55:46.302409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b14eba0548ae'
down_revision: Union[str, None] = 'f90df87e03bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_data', 'ts_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('residences', 'ts_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('residences', 'ts_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('personal_data', 'ts_update',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
