"""add valid period constraints

Revision ID: d82165792acd
Revises: b14eba0548ae
Create Date: 2026-09-01 03:06:57.563204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82165792acd'
down_revision: Union[str, None] = 'b14eba0548ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_personal_data_valid_period', 'personal_data', 'valid_from < valid_to')
    op.create_check_constraint('ck_residences_valid_period', 'residences', 'valid_from < valid_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_residences_valid_period', 'residences', type_='check')
    op.drop_constraint('ck_personal_data_valid_period', 'personal_data', type_='check')
    # ### end Alembic commands ###
