"""add temporal fields

Revision ID: f90df87e03bd
Revises: 5922974c1abe
Create Date: 2026-09-01 02:47:15.324351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90df87e03bd'
down_revision: Union[str, None] = '5922974c1abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_data', sa.Column('ts_gen', sa.DateTime(), nullable=False))
    op.add_column('personal_data', sa.Column('ts_update', sa.DateTime(), nullable=False))
    op.add_column('residences', sa.Column('ts_gen', sa.DateTime(), nullable=False))
    op.add_column('residences', sa.Column('ts_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residences', 'ts_update')
    op.drop_column('residences', 'ts_gen')
    op.drop_column('personal_data', 'ts_update')
    op.drop_column('personal_data', 'ts_gen')
    # ### end Alembic commands ###
